name: intercom_flutter
description: Flutter plugin for Intercom integration. Provides in-app messaging
  and help-center Intercom services
version: 2.3.4
homepage: https://github.com/v3rm0n/intercom_flutter

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.maido.intercom
        pluginClass: IntercomFlutterPlugin
      ios:
        pluginClass: IntercomFlutterPlugin
      web:
        pluginClass: IntercomWeb
        fileName: src/intercom_web.dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.7 <2.0.0"
